AWSTemplateFormatVersion: 2010-09-09
Description: "this template provision our dev network environment"
Metadata: {}

Parameters: {} 

Mappings: {}

Conditions: {}

Resources: 
  #devolpment vpc
  DevVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: DevVPC

  #Webserver subnet
  DevWebserverSubent:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref DevVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: DevWebserverSubent

  #Appserver subnet
  DevAppserverSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref DevVPC
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: DevAppserverSubnet

  #Debserver subnet
  DebserverSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref DevVPC
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: DebserverSubnet

Outputs: {}